name: Sync labels

on:
    push:
        branches:
            - production
            - develop
        paths:
            - '.github/labels.yml'
            - '.github/workflows/labels-sync.yml'

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
    update_labels:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Apply labels
              uses: crazy-max/ghaction-github-labeler@v5
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  yaml-file: .github/labels.yml
                  skip-delete: false
